# License key Value!!
#key=5W9yHHYzjOyYUr9i0C5xPtAj2dQKdh6i34bKoDDrtF39cPFXu8CndxyxI5YZizhO7A9qIj0x/D7OXmo4AnjfjfLQsYKmQeds83Eaub26r4iEDcM8ZfxbzPKK/dGfIWxNBDB+E7h3SN9Njfrp2OTAXZmlj9dWPtuQCa8ENrPdkbwHC4HtFgF+1/k4LuLDShPx

# \uac1c\ubc1c \ub77c\uc774\uc13c\uc2a4 (202308)
key=5W9yHHYzjOyYUr9i0C5xPhZNbBJ4cnEy34bKoDDrtF39cPFXu8CndwO1s7dwE3aEXGd+NTCF+J8AU9kVFRH6kg21DdZUgz/RqnMEZ1YVtvgp0bsm6Tup/zLGZ2M16EpB1R7r9FYkt8FT9m5CQDKRWgoj9HoPoWcRmxRDliNb6m3Yj2DgWMYX+hGtsSTizjknzsMwlMGwjzokcAdscufOdQ==