#***********************************************************************
#     globals.properties : Dev Property
#***********************************************************************

# Server Type

isry.globals.ostype =LINUX

# Profile Type 
isry.globals.profile =dev2

# .Dev File UPLoad Root Path  
isry.globals.wasupload.file.folder=/uploadfiles/was/
isry.globals.webupload.file.folder=/uploadfiles/web/
# ilb = isry_local_backend
# idb = isry_dev_backend
# irb = isry_real_backend
# itb = isry_test_backend
isry.globals.service.name=idb

isry.globals.cmn.fileStorePath=cmn

####################################################
#    DB Enc Solution  DAMO Config Path Song.Young.Il
####################################################
isry.globals.damo.path=/sw/damo/scpdb_agent.ini

isry.globals.damo.info=KEY1

# \uc554\ud638\ud654 \ud14c\uc2a4\ud2b8\ub97c \uc704\ud55c \uc18c\uc2a4 \ud30c\uc77c 
# \ud14c\uc2a4\ud2b8\uc6a9 \uc0d8\ud50c \ud654\uc77c 
isry.globals.damo.sourcefile.path=/tmp/isry_damo_test.txt

# \uc554\ud638\ud654 \ub300\uc0c1 \ud30c\uc77c \ud328\uc2a4 
isry.globals.damo.encfile.path=/tmp/isry_damo_test.enc

# \ubcf5\ud638\ud654 \ub300\uc0c1 \ud30c\uc77c \ud328\uc2a4
isry.globals.damo.decfile.path=/tmp/isry_damo_test.dec

#####################################################
# \ud30c\uc77c \uc5c5\ub85c\ub4dc \ucc98\ub9ac POLICY
isry.uploadpolicy.default.allow = *.jpg;*.png;*.gif;*.jpeg;*.tif;*.tiff;*.jfif;*.bmp;*.txt;*.hwp;*.hwpx;*.docx;*.doc;*.docm;*.ppt;*.pptx;*.pptm;*.pps;*.ppsx;*.xls;*.xlsx;*.xlsm;*.xlam;*.xla;*.psd;*.pdf;*.ods;.ogg;*.mp4;*.avi;*.wmv;*.zip;*.rar;*.tar;*.7z;*.tbz;*.tgz;*.lzh;*.gz;*.ai;

isry.uploadpolicy.default.deny = *

isry.uploadpolicy.default.maxfilesize = 1024000000

#####################################################

# \uac1c\uc778\uc815\ubcf4 \ud544\ud130\ub9c1 API \uc5f0\uacb0 \uc815\ubcf4
# \uac1c\ubc1c\uc11c\ubc84 API URL
isry.globals.privacy.url = http://10.33.2.59:80/safer/upcloud/privacys
# \uc6b4\uc601\uc11c\ubc84 API URL(\uc778\ud130\ub137\ub9dd-WAS1)
#isry.globals.privacy.url = http://10.188.91.183:80/safer/upcloud/privacys
isry.server.dev.ip   = 10.33.2.59
isry.server.dev.port = 80

#####################################################

# \uc8fc\uc18c \uc11c\ube44\uc2a4 \uc774\uc9c0\uc12d 
juso.update.folder =/tmp
juso.update.appKey = U01TX0FVVEgyMDIxMTIxMDEwMTczODExMjAxMzk=
juso.update.ip = 10.182.60.20
juso.update.port = 9300

juso.search.appKey = U01TX0FVVEgyMDIyMDQwNjE1MjEzMjExMjQyNDQ=

# \uc124\ubb38\uc9c0\ubc1c\uc1a1 \uc2e0\uccad\uc790 \uc811\uadfc \ub3c4\uba54\uc778 \uacbd\ub85c
srvy.recv.url = http://10.33.2.59:8880/svcreq

# \ub85c\uadf8\uc778 \uacf5\uc9c0\uc0ac\ud56d \uac8c\uc2dc\ud310 \ubc88\ud638
#isry.loginNoticeBoardNo = 10142
isry.loginNoticeBoardNo = 10201

isry.nas.sync.server = 10.33.2.77:13000;
