#***********************************************************************
#    REAL Property globals.properties  
#***********************************************************************

# Server Type

isry.globals.ostype =LINUX

# Profile Type 
isry.globals.profile =real2

# .Dev File UPLoad Root Path  
isry.globals.wasupload.file.folder=/nas_data/was/
isry.globals.webupload.file.folder=/nas_data/web/
isry.globals.service.name=isry_backend

isry.globals.cmn.fileStorePath=cmn
####################################################
#    DB Enc Solution  DAMO Config Path Song.Young.Il
####################################################
isry.globals.damo.path=/sw/damo/scpdb_agent.ini

isry.globals.damo.info=KEY1

# \uc554\ud638\ud654 \ud14c\uc2a4\ud2b8\ub97c \uc704\ud55c \uc18c\uc2a4 \ud30c\uc77c 
# \ud14c\uc2a4\ud2b8\uc6a9 \uc0d8\ud50c \ud654\uc77c 
isry.globals.damo.sourcefile.path=/tmp/isry_damo_test.txt

# \uc554\ud638\ud654 \ub300\uc0c1 \ud30c\uc77c \ud328\uc2a4 
isry.globals.damo.encfile.path=/tmp/isry_damo_test.enc

# \ubcf5\ud638\ud654 \ub300\uc0c1 \ud30c\uc77c \ud328\uc2a4
isry.globals.damo.decfile.path=/tmp/isry_damo_test.dec

#####################################################
# \ud30c\uc77c \uc5c5\ub85c\ub4dc \ucc98\ub9ac POLICY
isry.uploadpolicy.default.allow = *.jpg;*.png;*.gif;*.jpeg;*.tif;*.tiff;*.jfif;*.bmp;*.txt;*.hwp;*.hwpx;*.docx;*.doc;*.docm;*.ppt;*.pptx;*.pptm;*.pps;*.ppsx;*.xls;*.xlsx;*.xlsm;*.xlam;*.xla;*.psd;*.pdf;*.ods;.ogg;*.mp4;*.avi;*.wmv;*.zip;*.rar;*.tar;*.7z;*.tbz;*.tgz;*.lzh;*.gz;*.ai;

isry.uploadpolicy.default.deny = *

isry.uploadpolicy.default.maxfilesize = 1024000000

#####################################################

# \uac1c\uc778\uc815\ubcf4 \ud544\ud130\ub9c1 API \uc5f0\uacb0 \uc815\ubcf4
# \uac1c\ubc1c\uc11c\ubc84 API URL
#isry.globals.privacy.url = http://10.33.2.59:80/safer/upcloud/privacys
# \uc6b4\uc601\uc11c\ubc84 API URL(\uc778\ud130\ub137\ub9dd-WAS1)
isry.privacy.url = http://10.188.91.183:8081/safer/upcloud/privacys
isry.server.ip   = 10.188.91.183
isry.server.port = 8081

#####################################################

# \uc6b4\uc601\uc11c\ubc84-\uc8fc\uc18c \uc11c\ube44\uc2a4 \uc774\uc9c0\uc12d 
juso.update.folder =/tmp
juso.update.appKey = U01TX0FVVEgyMDIxMTIxMDEwMTczODExMjAxMzk=
juso.update.ip = 10.182.60.20
juso.update.port = 9300

juso.search.appKey = U01TX0FVVEgyMDIyMDQwNjE1MjMzODExMjQyNzA=


################## \uae43\ud50c\ucc57 \uc815\ubcf4 \uc724\ud76c\uc131  #############################
# \uae43\ud50c\ucc57 secret
isry.gitple.secret01 =eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IjA6MTY1Mjc2NTkxMTAxODo0OjQ6bzo6b3Mi.8l2QiNwF72HRHFltTTr-PZfi6JkjoQ6WohabiEQlizw
isry.gitple.secret02 =eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IjA6MTY1Mjc3ODE4NTU3Mjo0OjU6bzo6b3Mi.f-eRM6RmqBKxilLKjXy6BPP9QkbFGllIFnkIoERXyEs
isry.gitple.secret03 =eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IjA6MTY1NjkwMTA1ODEwNTo0OjY6bzo6b3Mi._Jb--T2KK5B9NSi31akNfK5Rm1eKH9lDfEbYcNslKb4
isry.gitple.secret04 =eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IjA6MTY1NjkwMTEwNzg3ODo0Ojg6bzo6b3Mi.ZdMRghqu5QLcQCTEYw-0ouOmz-OnX3fwVhRH4ufksnQ
isry.gitple.secret05 =eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IjA6MTY1NjkwMTEzNDU4Mzo0OjExOm86Om9zIg.P0powxDTztlcyhIdjcR3bdBjzSjc4lJ3h-UbLZ2mKAQ
isry.gitple.secret06 =eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IjA6MTY1NjkwMTE3MzM2Nzo0OjEzOm86Om9zIg.ByRRvlIsM__u63CSI65amAnz7JQt7XKpHjH5dGGkXso
isry.gitple.secret07 =eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IjA6MTY1NjkwMTIwODAzNzo0OjE0Om86Om9zIg.AdWl0rJUbYN0G_P7xJ7cmzh4boOgkBsgPd3ThoZagwg
isry.gitple.secret08 =eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IjA6MTY1MjkyMDE0MTgzNzo0OjE2Om86Om9zIg.IKWdbpVXAfTbq1yFSLtMfoWWDXWH3GybUvGHftronP8
isry.gitple.logout   =eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IjA6MTY3MTYwNjY3NzcyMTo0Oio6bzo6b3NzIg.8R8eFksU5H8m5ejVth6d2xqhQrKafNWOheAM3qVQRb0

# \uc124\ubb38\uc9c0\ubc1c\uc1a1 \uc2e0\uccad\uc790 \uc811\uadfc \ub3c4\uba54\uc778 \uacbd\ub85c
srvy.recv.url = https://gov.youthsafety.go.kr/svcreq


# \ub85c\uadf8\uc778 \uacf5\uc9c0\uc0ac\ud56d \uac8c\uc2dc\ud310 \ubc88\ud638
isry.loginNoticeBoardNo = 10201

isry.nas.sync.server = 10.188.131.221:13000;10.188.131.222:13000;10.188.131.223:13000;10.188.131.224:13000;
