#***********************************************************************
#     globals.properties : \uc804\uc790\uc815\ubd80 \ud504\ub808\uc784\uc6cc\ud06c \uc804\uccb4 \ud504\ub77c\ud37c\ud2f0  
#***********************************************************************


#   1.  key = value \uad6c\uc870\uc785\ub2c8\ub2e4.
#   2.  key\uac12\uc740 \uacf5\ubc31\ubb38\uc790\ub97c \ud3ec\ud568\ubd88\uac00, value\uac12\uc740 \uacf5\ubc31\ubb38\uc790\ub97c \uac00\ub2a5
#   3.  key\uac12\uc73c\ub85c \ud55c\uae00\uc744 \uc0ac\uc6a9\ubd88\uac00,   value\uac12\uc740 \ud55c\uae00\uc0ac\uc6a9\uc774 \uac00\ub2a5
#   4.  \uc904\uc744 \ubc14\uafc0 \ud544\uc694\uac00 \uc788\uc73c\uba74 '\'\ub97c \ub77c\uc778\uc758 \ub05d\uc5d0 \ucd94\uac00(\ub9cc\uc57d  '\'\ubb38\uc790\ub97c \uc0ac\uc6a9\ud574\uc57c \ud558\ub294 \uacbd\uc6b0\ub294 '\\'\ub97c \uc0ac\uc6a9)
#   5.  Windows\uc5d0\uc11c\uc758 \ub514\ub809\ud1a0\ub9ac \ud45c\uc2dc : '\\' or '/'  ('\' \uc0ac\uc6a9\ud558\uba74 \uc548\ub428)
#   6.  Unix\uc5d0\uc11c\uc758 \ub514\ub809\ud1a0\ub9ac \ud45c\uc2dc : '/'
#   7.  \uc8fc\uc11d\ubb38 \ucc98\ub9ac\ub294  #\uc0ac\uc6a9
#   8.  value\uac12 \ub4a4\uc5d0 \uc2a4\ud398\uc774\uc2a4\uac00 \uc874\uc7ac\ud558\ub294 \uacbd\uc6b0 \uc11c\ube14\ub9bf\uc5d0\uc11c \ucc38\uc870\ud560\ub54c\ub294 \uc5d0\ub7ec\ubc1c\uc0dd\ud560 \uc218 \uc788\uc73c\ubbc0\ub85c trim()\ud558\uac70\ub098 \ub9c8\uc9c0\ub9c9 \uacf5\ubc31\uc5c6\uc774 properties \uac12\uc744 \uc124\uc815\ud560\uac83
#-----------------------------------------------------------------------

# \uc6b4\uc601\uc11c\ubc84 \ud0c0\uc785(WINDOWS, UNIX)

isry.globals.ostype =WINDOWS

isry.globals.profile =local

# .\ub85c\uceec  \ud30c\uc77c \uc5c5\ub85c\ub4dc \ub8e8\ud2b8 \ud328\uc2a4 
isry.globals.wasupload.file.folder=C:\\development\\fileupload\\was\\
isry.globals.webupload.file.folder=C:\\development\\fileupload\\web\\
# ilb = isry_local_backend
# idb = isry_dev_backend
# irb = isry_real_backend
# itb = isry_test_backend
isry.globals.service.name=ilb

isry.globals.cmn.fileStorePath=cmn

#######################################################
#  DB Enc Solution  DAMO Config Path Song.Young.Il
#######################################################
isry.globals.damo.path=C:\\development\\bin\\damo\\scpdb_agent.ini
 
 
# DAMO \uc0ac\uc6a9\ud558\ub294 \uceec\ub7fc\uba85\uc784. 
isry.globals.damo.info=KEY1

# \uc554\ud638\ud654 \ud14c\uc2a4\ud2b8\ub97c \uc704\ud55c \uc18c\uc2a4 \ud30c\uc77c 
# \uc554\ud638\ud654 \ud14c\uc2a4\ud2b8\uc6a9 txt \uc0d8\ud50c \ud654\uc77c\uc784
isry.globals.damo.sourcefile.path=C:\\development\\bin\\damo\\isry_damo_test.txt

# \uc554\ud638\ud654 \ub300\uc0c1 \ud30c\uc77c \ud328\uc2a4 
isry.globals.damo.encfile.path=C:\\development\\bin\\damo\\isry_damo_test.enc

# \ubcf5\ud638\ud654 \ub300\uc0c1 \ud30c\uc77c \ud328\uc2a4
isry.globals.damo.decfile.path=C:\\development\\bin\\damo\\isry_damo_test.dec

#####################################################

# \ud30c\uc77c \uc5c5\ub85c\ub4dc \ucc98\ub9ac POLICY
isry.uploadpolicy.default.allow = *.png;*.jpg;*.jpeg;*.gif;*.txt;*.csv;*.doc;*.docx;*.ppt;*.pptx;*.pdf;*.hwp;*.hwpx;*.xls;*.xlsx;*.zip;*.7z;
isry.uploadpolicy.default.deny = *
# \ud30c\uc77c \ucd5c\ub300 \uc6a9\ub7c9(500MB)
#isry.uploadpolicy.default.maxfilesize = 524288000
isry.uploadpolicy.default.maxfilesize = 1024000000

#####################################################

# \uac1c\uc778\uc815\ubcf4 \ud544\ud130\ub9c1 API \uc5f0\uacb0 \uc815\ubcf4
# \uac1c\ubc1c\uc11c\ubc84 API URL
isry.globals.privacy.url = http://10.33.2.59:80/safer/upcloud/privacys
# \uc6b4\uc601\uc11c\ubc84 API URL(\uc778\ud130\ub137\ub9dd-WAS1)
#isry.globals.privacy.url = http://10.188.91.183:80/safer/upcloud/privacys
isry.server.dev.ip= 10.33.2.59
isry.server.dev.port= 80

################## \uc8fc\uc18c \uc815\ubcf4 \uc774\uc9c0\uc12d  #############################
juso.update.folder = C:/development/jusofiles
juso.update.appKey = U01TX0FVVEgyMDIxMTIxMDExMzgxNjExMjAxNDE=
juso.update.ip = 10.182.60.20
juso.update.port = 9300

juso.search.appKey = U01TX0FVVEgyMDIyMDQwNjE1MjEzMjExMjQyNDQ=


################## \uae43\ud50c\ucc57 \uc815\ubcf4 \uc724\ud76c\uc131  #############################
# \uae43\ud50c\ucc57 secret
isry.gitple.secret01 =eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IjA6MTY1Mjc2NTkxMTAxODo0OjQ6bzo6b3Mi.8l2QiNwF72HRHFltTTr-PZfi6JkjoQ6WohabiEQlizw
isry.gitple.secret02 =eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IjA6MTY1Mjc3ODE4NTU3Mjo0OjU6bzo6b3Mi.f-eRM6RmqBKxilLKjXy6BPP9QkbFGllIFnkIoERXyEs
isry.gitple.secret03 =eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IjA6MTY1NjkwMTA1ODEwNTo0OjY6bzo6b3Mi._Jb--T2KK5B9NSi31akNfK5Rm1eKH9lDfEbYcNslKb4
isry.gitple.secret04 =eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IjA6MTY1NjkwMTEwNzg3ODo0Ojg6bzo6b3Mi.ZdMRghqu5QLcQCTEYw-0ouOmz-OnX3fwVhRH4ufksnQ
isry.gitple.secret05 =eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IjA6MTY1NjkwMTEzNDU4Mzo0OjExOm86Om9zIg.P0powxDTztlcyhIdjcR3bdBjzSjc4lJ3h-UbLZ2mKAQ
isry.gitple.secret06 =eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IjA6MTY1NjkwMTE3MzM2Nzo0OjEzOm86Om9zIg.ByRRvlIsM__u63CSI65amAnz7JQt7XKpHjH5dGGkXso
isry.gitple.secret07 =eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IjA6MTY1NjkwMTIwODAzNzo0OjE0Om86Om9zIg.AdWl0rJUbYN0G_P7xJ7cmzh4boOgkBsgPd3ThoZagwg
isry.gitple.secret08 =eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IjA6MTY1MjkyMDE0MTgzNzo0OjE2Om86Om9zIg.IKWdbpVXAfTbq1yFSLtMfoWWDXWH3GybUvGHftronP8
isry.gitple.logout   =eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IjA6MTY3MTYwNjY3NzcyMTo0Oio6bzo6b3NzIg.8R8eFksU5H8m5ejVth6d2xqhQrKafNWOheAM3qVQRb0

# \uc124\ubb38\uc9c0\ubc1c\uc1a1 \uc2e0\uccad\uc790 \uc811\uadfc \ub3c4\uba54\uc778 \uacbd\ub85c
srvy.recv.url = http://localhost:8888/svcreq

# \ub85c\uadf8\uc778 \uacf5\uc9c0\uc0ac\ud56d \uac8c\uc2dc\ud310 \ubc88\ud638
# isry.loginNoticeBoardNo = 10142
isry.loginNoticeBoardNo = 10004

isry.nas.sync.server = 10.33.2.77:13000;