

# ===================================================== 
#                src/main/resources Config              
# ===================================================== 

#scpdb_agent.ini
[KEYINFO]
KEY1=/sw/damo/ARIA_256_DEV.SCPS
#KEY2=SCP_FilePath
#KEY3=ServiceID,SCP_FILEPATH
[SERVER]
ServerIP=127.0.0.1
ServerPort=2525
[SERVER2]
ServerIP=127.0.0.1
ServerPort=2525
[TIMEOUT]
ConnectTimeout=2
SendTimeout=2
RecvTimeout=2
[POLICYSERVER]
PolicyServerIP=
PolicyServerPort=
PolicyServerTimeout=
[AGENT]
AgentID=
LicenseFilePath=/sw/damo/scpdb_license.cer
LogDir=
#LogLevel=0.NO / 4.LEVEL4_ERROR / 6.LEVEL6_NOTICE / 8.LEVEL8_DEBUG
LogLevel=0
LogCount=10000
LogCountType=1
LogCountTime=0
SiteCertFilePath=
CertFilePath=
KeyFilePath=
SPIN=
#Partial Encryption CharSet=0.NO / 1.EUC-KR / 2.UTF-8
CharSet=0
#Partial Encryption Type=0.OLD / 1.NEW
PartialEncType=0
#KMS Communication Version=100 / 102
PKP=100
AclPKP=102
#KMS Communication Data Version=102 / 103 / 104 / 105 / 106 / 107 / 109
#102: ~ SG-KMS 3.0.1.4
#103: ~ SG-KMS 3.0.2.0
#104: ~ SG-KMS 3.0.2.4
#105: ~ SG-KMS 3.0.4.0
#106: ~ SG-KMS 3.0.7.1
#107: ~ SG-KMS 3.0.16.1
#109: ~ 
PKD=109
#FileKeyInfo=0.NO / 1.YES
FileKeyInfo=0
#DiscernMode=0.NO / 1.All YES  / 2.Follows the service policy set to KMS
DiscernMode=0
DiscernChar=@^
#DiscernAfter=0.NO / 1.YES
DiscernAfter=0
ZeroLengthMode=0
#GroupKeyBackupMode=0.NO / 1.YES
GroupKeyBackupMode=0
GroupKeyBackupDir=
IniBackupDir=
#extraData
#AsymmCacheMode=0.NO / 1.YES
AsymmCacheMode=0
#Version=
#bypass
#scpdb_agent.ini
[KEAPI]
#KE-Win API Policy Type=FILE / KMS
PolicyType=FILE
PolicyName=D:\BA-SCP\Test\ke-win_api_test\ke-win.key
#PolicyName=D:\BA-SCP\Test\key\KE_WIN_API_TEST.scps
#PolicyName=KE_WIN_API_TEST
#[AGENT_CONF2]
#iniFilePath=D:\BA-SCP\Test\scpdb_agent_2.ini
